<?php echo $this->doctype() ?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Car Pooling Urbino</title>
<?php
	$this->headLink()->appendStylesheet($this->baseUrl() . '/css/blueprint/screen.css', "screen, projection");
	$this->headLink()->appendStylesheet($this->baseUrl() . '/css/blueprint/print.css', "print");
	$this->headLink()->appendStylesheet($this->baseUrl() . '/css/blueprint/ie.css', "screen,projection", true);
    echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/global.css', 'screen, projection') ?>
		<!--[if IE]><link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->
    </head>
    <body>
        <div class="container">
            <div class="block">
                <div id="header" class="column span-24">
                    <h1>Car Pond</h1>
                </div>
            </div>
            <div class="block">
                <div id="content" class="column span-16">
                <?php echo $this->layout()->content ?>
                </div>
                <div id="sidebar" class="column span-7">Sidebar</div>
            </div>
            <div class="block">
                <div id="footer" class="column span-24">
                    <p>Copyright &copy; 2009 <a href="http://www.sbisinger.net/">Stéphane Bisinger</a></p>
                </div>
            </div>
        </div>
    </body>
</html>
