<?php echo $this->doctype() ?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Car Pooling Urbino</title>
<?php
	$this->headLink()->appendStylesheet($this->baseUrl() . '/css/blueprint/screen.css', "screen, projection");
	$this->headLink()->appendStylesheet($this->baseUrl() . '/css/blueprint/print.css', "print");
	$this->headLink()->appendStylesheet($this->baseUrl() . '/css/blueprint/ie.css', "screen,projection", true);
        echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/global.css', 'screen, projection') ?>
	<!--[if IE]><link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->
	  <?php
	  if($this->dojo()->isEnabled()) {
	    $this->dojo()
	      ->addStylesheetModule('dijit.themes.tundra')
	      ->setLocalPath($this->baseUrl() . '/js/dojo/dojo/dojo.js');
	    echo $this->dojo();
	  }
	  echo $this->headScript();
	  ?>
    </head>
    <body class="tundra">
        <div class="container">
			<div id="header" class="column span-24">
				<h1>Car Pond</h1>
			</div>
			<div id="menu" class="column span-24">
				<ul>
					<li><a href="<?php echo $this->baseUrl();?>/">Home</a></li>
					<li><a href="<?php echo $this->baseUrl();?>/signup">Registrati</a></li>
					<li><a href="<?php echo $this->baseUrl();?>/login">Accedi</a></li>
					<li><a href="<?php echo $this->baseUrl();?>/ride/search">Ricerca</a></li>
				</ul>
			</div>
			<div id="content" class="column span-16">
	  <?php echo $this->layout()->content; ?>
	  <?php echo $this->inlineScript();?>
			</div>
			<div id="sidebar" class="column span-7">Sidebar</div>
			<div id="footer" class="column span-24">
				<p>Copyright &copy; 2009 <a href="http://www.sbisinger.net/">Stéphane Bisinger</a></p>
			</div>
        </div>
    </body>
</html>
